export const dateConstants = {
  // for client state management
  SET_DELETE_EVENT: 'SET_DELETE_EVENT',
  REMOVE_DELETE_EVENT: 'REMOVE_DELETE_EVENT',
  SET_NAV: 'SET_NAV',
  SET_DATE_DISPLAY: 'SET_DATE_DISPLAY',
  SET_DAY_ARRAY: 'SET_DAY_ARRAY',
  SET_CLICKED_EVENT: 'SET_CLICKED_EVENT',
  "SET_CALENDER_TYPE": "SET_CALENDER_TYPE",

  // for both client and server
  SET_EVENTS_REQUEST: 'SET_EVENTS_REQUEST',
  SET_EVENTS_SUCCESS: 'SET_EVENTS_SUCCESS',
  SET_EVENTS_FAILURE: 'SET_EVENTS_FAILURE',
  GET_EVENTS_REQUEST: 'GET_EVENTS_REQUEST',
  GET_EVENTS_SUCCESS: 'GET_EVENTS_SUCCESS',
  GET_EVENTS_FAILURE: 'GET_EVENTS_FAILURE',
  DELETE_EVENTS_REQUEST: 'DELETE_EVENTS_REQUEST',
  DELETE_EVENTS_SUCCESS: 'DELETE_EVENTS_SUCCESS',
  DELETE_EVENTS_FAILURE: 'DELETE_EVENTS_FAILURE',
  UPDATE_EVENTS_REQUEST: 'UPDATE_EVENTS_REQUEST',
  UPDATE_EVENTS_SUCCESS: 'UPDATE_EVENTS_SUCCESS',
  UPDATE_EVENTS_FAILURE: 'UPDATE_EVENTS_FAILURE',
  GET_TODAYS_EVENTS_REQUEST: 'GET_TODAYS_EVENTS_REQUEST',
  GET_TODAYS_EVENTS_SUCCESS: 'GET_TODAYS_EVENTS_SUCCESS',
  GET_TODAYS_EVENTS_FAILURE: 'GET_TODAYS_EVENTS_FAILURE',


};

export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  CHECK_SESSION_REQUEST: 'CHECK_SESSION_REQUEST',
  CHECK_SESSION_SUCCESS: 'CHECK_SESSION_SUCCESS',
  CHECK_SESSION_FAILURE: 'CHECK_SESSION_FAILURE',
};
export const userConstants = {
  GET_AVA_TEA_REQUEST: 'GET_AVA_TEA_REQUEST',
  GET_AVA_TEA_SUCCESS: 'GET_AVA_TEA_SUCCESS',
  GET_AVA_TEA_FAILURE: 'GET_AVA_TEA_FAILURE',
  GET_SEARCHED_TEA_REQUEST: 'GET_SEARCHED_TEA_REQUEST',
  GET_SEARCHED_TEA_SUCCESS: 'GET_SEARCHED_TEA_SUCCESS',
  GET_SEARCHED_TEA_FAILURE: 'GET_SEARCHED_TEA_FAILURE',
  "SET_SEARCHED":"SET_SEARCHED"
};
export const weekConstants = {
  "SET_WEEK": "SET_WEEK",
  "SET_WEEK_COUNTER": "SET_WEEK_COUNTER",
  "SET_PADDINGWEEK_DAY": "SET_PADDINGWEEK_DAY",
  "SET_DAY": "SET_DAY",
  "SET_DAY_COUNTER": "SET_DAY_COUNTER"
};
